[package]
name = "deai_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0.171", features = ["derive"] }
candid = "0.10.3"
ic-cdk = "0.14"
strum = "0.27.1"
strum_macros = "0.27.1"

